# Generated by Django 5.2.13 on 2026-05-01 00:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=150)),
                ('telefone', models.CharField(max_length=30, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('ponto_referencia', models.CharField(blank=True, max_length=255)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoMarmitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome_empresa', models.CharField(max_length=150)),
                ('telefone_atendimento', models.CharField(max_length=30)),
                ('chave_pix', models.CharField(blank=True, max_length=120)),
                ('horario_funcionamento', models.CharField(blank=True, max_length=255)),
                ('taxa_entrega_padrao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('mensagem_boas_vindas', models.TextField(blank=True)),
                ('mensagem_fora_horario', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('marmita_pequena', 'Marmita pequena'), ('marmita_media', 'Marmita media'), ('marmita_grande', 'Marmita grande'), ('bebida', 'Bebida'), ('adicional', 'Adicional'), ('sobremesa', 'Sobremesa')], max_length=30)),
                ('disponivel', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ia', 'IA'), ('humano', 'Humano'), ('finalizada', 'Finalizada')], default='ia', max_length=20)),
                ('ultima_mensagem', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='app.cliente')),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('cliente', 'Cliente'), ('ia', 'IA'), ('humano', 'Humano'), ('sistema', 'Sistema')], max_length=20)),
                ('texto', models.TextField(blank=True)),
                ('whatsapp_message_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='app.conversa')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aguardando_confirmacao', 'Aguardando confirmacao'), ('aguardando_pagamento', 'Aguardando pagamento'), ('pago', 'Pago'), ('em_preparo', 'Em preparo'), ('saiu_para_entrega', 'Saiu para entrega'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='rascunho', max_length=30)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('cartao_entrega', 'Cartao na entrega')], max_length=30)),
                ('endereco_entrega', models.CharField(blank=True, max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app.cliente')),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app.conversa')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido', to='app.produto')),
            ],
        ),
    ]
