# Generated by Django 5.2.13 on 2026-05-31 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoConversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status_atendimento', models.CharField(default='inicio', max_length=50)),
                ('ultima_intencao', models.CharField(blank=True, max_length=50)),
                ('itens_pedido', models.JSONField(blank=True, default=list)),
                ('itens_pendentes', models.JSONField(blank=True, default=list)),
                ('tipo_entrega', models.CharField(blank=True, max_length=30)),
                ('produto', models.CharField(blank=True, max_length=50)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('valor_unitario', models.FloatField(default=0.0)),
                ('valor_total', models.FloatField(default=0.0)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('forma_pagamento', models.CharField(blank=True, max_length=30)),
                ('aguardando_resposta', models.CharField(blank=True, max_length=50)),
                ('conversa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_fluxo', to='app.conversa')),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
