# Generated by Django 5.2.13 on 2026-06-03 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_seed_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaomarmitaria',
            name='aceita_entrega',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaomarmitaria',
            name='aceita_pedidos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaomarmitaria',
            name='aceita_retirada_local',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaomarmitaria',
            name='endereco_retirada',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuracaomarmitaria',
            name='pedido_maximo_sem_consulta',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='CardapioDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dia_semana', models.CharField(choices=[('segunda-feira', 'Segunda-feira'), ('terca-feira', 'Terca-feira'), ('quarta-feira', 'Quarta-feira'), ('quinta-feira', 'Quinta-feira'), ('sexta-feira', 'Sexta-feira'), ('sabado', 'Sabado'), ('domingo', 'Domingo')], max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('descricao', models.TextField(help_text='Liste os itens do dia. Pode usar uma linha por item ou bullets.')),
                ('ativo', models.BooleanField(default=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardapios_dia', to='app.configuracaomarmitaria')),
            ],
            options={
                'ordering': ['dia_semana'],
                'constraints': [models.UniqueConstraint(fields=('configuracao', 'dia_semana'), name='unique_cardapio_por_configuracao_dia')],
            },
        ),
        migrations.CreateModel(
            name='HorarioFuncionamentoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dia_semana', models.CharField(choices=[('segunda-feira', 'Segunda-feira'), ('terca-feira', 'Terca-feira'), ('quarta-feira', 'Quarta-feira'), ('quinta-feira', 'Quinta-feira'), ('sexta-feira', 'Sexta-feira'), ('sabado', 'Sabado'), ('domingo', 'Domingo')], max_length=20)),
                ('fechado', models.BooleanField(default=False)),
                ('abre_pedidos', models.TimeField(blank=True, null=True)),
                ('fecha_pedidos', models.TimeField(blank=True, null=True)),
                ('abre_entregas', models.TimeField(blank=True, null=True)),
                ('fecha_entregas', models.TimeField(blank=True, null=True)),
                ('abre_retiradas', models.TimeField(blank=True, null=True)),
                ('fecha_retiradas', models.TimeField(blank=True, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=255)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_funcionamento', to='app.configuracaomarmitaria')),
            ],
            options={
                'ordering': ['dia_semana'],
                'constraints': [models.UniqueConstraint(fields=('configuracao', 'dia_semana'), name='unique_horario_por_configuracao_dia')],
            },
        ),
    ]
